### ISSUE TITLE
Compilation fails on FreeBSD 13.0

### ISSUE THREAD

**Issue by Huskers2020** [Amzo/FreeBSD-Tensorflow#2]
I get the following error, did you run into this issue?

My protobuf version 3.17

FreeBSD-Tensorflow-master/science/py-tensorflow/work-py38/tensorflow-2.1.4/tensorflow/core/platform/BUILD:53:1: C++ compilation of rule '//tensorflow/core/platform:human_readable_json_impl' failed (Exit 1)
tensorflow/core/platform/default/human_readable_json.cc:36:29: error: no member named 'error_message' in 'google::protobuf::util::status_internal::Status'
    auto error_msg = status.error_message();
                     ~~~~~~ ^
tensorflow/core/platform/default/human_readable_json.cc:54:29: error: no member named 'error_message' in 'google::protobuf::util::status_internal::Status'
    auto error_msg = status.error_message();
                     ~~~~~~ ^
2 errors generated.
INFO: Elapsed time: 30.370s, Critical Path: 8.25s
INFO: 8 processes: 8 local.
FAILED: Build did NOT complete successfully
*** Error code 1

**Comment by Amzo** [comment]
Currently working on a build of 2.9.1 on FreeBSD 13.1. However, the bazel build system has switched to external toolchains where bazel fetches the rules remotely during build. As ports doesn't allow fetching during build, I have to find a way to resolve this issue to patch in a FreeBSD toolchain. Currently this blocks the progress of this.

**Comment by Amzo** [comment]
Linking currently fails and is the only block for a successful compile. See issues here:

https://github.com/llvm/llvm-project/issues/57560

**Comment by Amzo** [comment]
Tensorflow should now build successfully on FreeBSD 13. However, there is still some packaging issue to fix first.

```Python 3.9.13 (main, Aug 11 2022, 01:13:34) 
[Clang 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c on freebsd13
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf

>>> mnist = tf.keras.datasets.mnist
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/keras/__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation
ModuleNotFoundError: No module named 'tensorflow.keras'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 58, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/keras/__init__.py", line 5, in <module>
    raise ImportError(
ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`

```

This is an entirely different issues, so I will close this issue now and open a new one.
